version: 0.2

# for info on the build phases used here:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases

# for info on the buildspec.yml syntax:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - mkdir /root/artifacts              

  build:
    commands:
      - npm run lint > /root/artifacts/lint.log.txt 2>&1
      - tail -n 20     /root/artifacts/lint.log.txt

artifacts:
  files:
    - /root/artifacts/*
  discard-paths: yes
